/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/mnt/d/Nim/lib -o /mnt/d/npfs/nim-merkle-dag/nimcache/splitting.c.o /mnt/d/npfs/nim-merkle-dag/nimcache/splitting.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, nimGC_setStackBottom)(void* theStackBottom);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_parseutilsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_parseutilsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_bitopsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_bitopsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_mathInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_mathDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_algorithmInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_algorithmDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_unicodeInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_unicodeDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_strutilsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_strutilsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_typetraitsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_typetraitsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_optionsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_optionsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_macrosInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_macrosDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_strformatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_strformatDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_posixInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_posixDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_timesInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_timesDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_ospathsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_ospathsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_osInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_osDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
N_LIB_PRIVATE N_NIMCALL(void, splittingDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(void, initStackBottomWith)(void* locals) {
	nimGC_setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_bitopsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_unicodeDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_typetraitsDatInit000();
	stdlib_optionsDatInit000();
	stdlib_macrosDatInit000();
	stdlib_strformatDatInit000();
	stdlib_posixDatInit000();
	stdlib_timesDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	splittingDatInit000();
	stdlib_parseutilsInit000();
	stdlib_bitopsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_unicodeInit000();
	stdlib_strutilsInit000();
	stdlib_typetraitsInit000();
	stdlib_optionsInit000();
	stdlib_macrosInit000();
	stdlib_strformatInit000();
	stdlib_posixInit000();
	stdlib_timesInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}


static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
	nimfr_("splitting", "splitting.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, splittingDatInit000)(void) {
}

